openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22001
servers:
  - url: https://library.com
tags:
  - Books
  - Authors
  - Visitors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDateMin
          description: |
            If  `releaseDateMax` is not provided, `releaseDateMin` is ignored.
            `releaseDateMin` can not be after `releaseDateMax`.
          schema:
            type: string
            format: date
          required: false
        - in: query
          name: releaseDateMax
          description: |
            If  `releaseDateMin` is not provided, `releaseDateMax` is ignored.
            `releaseDateMax` can not be after `releaseDateMin`.
          schema:
            type: string
            format: date
          required: false
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
      responses:
        200:
          $ref: '#/components/responses/BookList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CrupdateBook'
      responses:
        200:
          $ref: '#/components/responses/BookList_200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      summary: Associate a single book to an author
      operationId: associateBookAuthor
      parameters:
        - name: bookId
          in: path
          schema:
            type: string
          required: true
        - name: authorId
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          $ref: '#/components/schemas/BookListBody'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /books/authors:
    put:
      tags:
        - Books
      summary: Associate some books to some authors
      operationId: associateBooksAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateBook'
      responses:
        200:
          $ref: '#/components/schemas/BookListBody'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /authors:
    get:
      summary: Get all authors
      operationId: getAuthors
      tags:
        - Authors
      parameters:
        - name: authorName
          in: query
          description: |
            Filter returned authors by given name. 
            If not provided, then list is not filtered.
          schema:
            type: string
          required: false
      responses:
        200:
          $ref: "#/components/responses/AuthorList_200"
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
    put:
      summary: Create or update authors
      operationId: crupdateAuthors
      tags:
        - Authors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /authors/page/{page}/size/{size}:
    get:
      tags:
        - Authors
      parameters:
        - in: path
          name: page
          schema:
            type: integer
          required: true
        - in: path
          name: size
          schema:
            type: integer
          required: true
      responses:
        200:
          description: The author deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /authors/{aId}:
    delete:
      summary: Delete an author
      operationId: deleteAuthor
      tags:
        - Authors
      parameters:
        - name: aId
          in: path
          description: Author identifier to be deleted
          schema:
            type: string
          required: true
      responses:
        200:
          description: The author deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /visitors: 
    get:
      tags:
        - "Visitors"
      summary: List of visitors 
      responses:
        200: 
          $ref: "#/components/responses/VisitorList_200" 
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
    post: 
      tags:
        - "Visitors"
      summary: Create new visitors 
      requestBody: 
        required: true 
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Visitor"
      responses:
        200: 
          $ref: "#/components/responses/VisitorList_200"
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /bookAvailable :
    get :
      tags:
        - "Books"
      summary: List of available books 
      responses:
        200: 
          $ref: "#/components/responses/BookList_200"
    post: 
      tags:
        - "Books"
      summary: borrow a book 
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Borrowing"
      security:
        - OAuth2: [admin]
      responses:
        200: 
          description: Borrowed
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Borrowing"
  /Books/{bookId}/borrow:
    post: 
      summary: Borrow a book
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of book borrowed
          schema: 
            type: string
      requestBody: 
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/BorrowRequest"
      responses:
        200: 
          description: Borrowed successfully
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Borrowing"
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
  /books/{bookId}/render:
    post: 
      summary: return a book borrowed
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of book to hand in
          schema: 
            type: string
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RendRequest'
      responses:
        200: 
          description: Book successfully delivered
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Rendering"
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        500 : 
          $ref: '#/components/responses/500'
components:
  parameters:
    Page:
      in: query
      name: page
      schema:
        type: integer
        default: 1
      required: false
    PageSize:
      in: query
      name: pageSize
      schema:
        type: integer
        default: 30
      required: false
  responses:
    BookList_200:
      description: List of books
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BookListBody'
    AuthorList_200:
      description: List filtered of authors.
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/AuthorListBody'
    VisitorList_200: 
      description: List of visitors
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VisitorListBody' 
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestBody'
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenBody'
    500:
      description: Internal Sever Error
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/InternalServerErrorBody'
  schemas:
    ResponseStatus:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: OK
    ResponseBodyTemplate:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ResponseStatus'
        body:
          type: object
    BadRequestBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 400
          message: BAD REQUEST
        body: { }
    ForbiddenBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 403
          message: FORBIDDEN
        body: { }
    InternalServerErrorBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
      example:
        status:
          code: 500
          message: INTERNAL SERVER ERROR 
          body: { }
    BookListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Book'
    AuthorListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items:
                $ref: '#/components/schemas/Author'
    VisitorListBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBodyTemplate'
        - properties:
            body:
              type: array
              items :
                $ref: '#/components/schemas/Visitor'
    Visitor: 
      type: object
      properties:
        id: 
          type: string 
        name : 
          type: string
        reference :
          type: string
    Book:
      type: object
      properties:
        author:
          $ref: '#/components/schemas/Author'
      allOf:
        - $ref: '#/components/schemas/CrupdateBook'
    Author:
      type: object
      properties:
        id:
          type: string
        authorName:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
    Sex:
      type: string
      enum:
        - M
        - F
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    UpdateBook :
      type: object
      properties:
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    Borrowing:
      type: object
      properties:
        id:
          type: string
        visitor: 
          $ref: "#/components/schemas/Visitor"
        book :
          $ref: "#/components/schemas/Book"
        loan_date:
          type: string
          format: date-time
    Rendering: 
      type: object
      properties:
        id: 
          type: string
        visitorId:
          type: string
        bookId: 
          type: string
        renderDate: 
          type: string
          format: date-time
    BorrowRequest:
      type: object
      properties:
        visitorId:
          type: string
          description: ID of visitor who borrow the book
    RendRequest:
      type: object
      properties:
        visitorId:
          type: string
          description: ID of visitor who rend the book
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: autorisation URL for OAuth
          tokenUrl: 'jeton URL of OAuth'
          scopes:
            admin: Administrator acces